### ISSUE TITLE
Data Visualisation  and NLP & SA for Reddit Stock Trends

### ISSUE THREAD

**Issue by amruthraghav** [iam-abbas/Reddit-Stock-Trends#13]
I would like to work on the NLP and SA for this project. Have experience in analysing financial texts before. Feel free to check my profile

**Comment by iam-abbas** [comment]
@amruthraghav that's fantastic! please feel free to create a fork and a new branch for yourself, Really excited to see how we can leverage NLP in this project!

**Comment by amruthraghav** [comment]
Thanks @iam-abbas, do we have any channels for discussion. I would like to suggest some modifications if that's cool. Have some ideas in mind if you are willing to implement.
