### ISSUE TITLE
Using praw.ini

### ISSUE THREAD

**Issue by pcheng17** [iam-abbas/Reddit-Stock-Trends#15]
Hey! Have you thought about using a top-level `praw.ini` to pass in your client id, client secret, and user_agent? See [here](https://praw.readthedocs.io/en/latest/getting_started/configuration/prawini.html) for its documentation.

Having a section in the `praw.ini` file that contains the following

`[ScraperBot]`
`client_id = ABCDE`
`client_secret = 12345`
`user_agent = ScraperBot`

would allow initialization of the `Reddit` object to simply be `reddit = praw.Reddit('ScraperBot')`. Plus, it would remove the current need for `dotenv`.

**Comment by iam-abbas** [comment]
That sounds really convenient! Could you make a PR?

**Comment by pcheng17** [comment]
Will do! Where in the directory structure do you expect you or other users to run the code? I want to make sure I'm putting the `praw.ini` file in the right spot since it needs to be in the same directory as where you're running the code.

**Comment by iam-abbas** [comment]
Added in #14
