### ISSUE TITLE
tqdm.std.TqdmKeyError

### ISSUE THREAD

**Issue by s0meguy1** [iam-abbas/Reddit-Stock-Trends#2]
Hello!

Love the idea! Just started playing around with it and ran into an issue. After setting up requirements.txt and doing my first run, I am getting this error:

```
Traceback (most recent call last):
  File "./ticker_counts.py", line 48, in <module>
    post.total_awards_received] for post in tqdm(new_bets, desc="Selecting relevant data from webscraper", limit=WEBSCRAPER_LIMIT)]
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1007, in __init__
    TqdmKeyError("Unknown argument(s): " + str(kwargs)))
tqdm.std.TqdmKeyError: "Unknown argument(s): {'limit': 2000}"
```

I do not know anything about tqdm and could not figure out the issue, any ideas @Denbergvanthijs? I only ping you because tqdm was added to the standalone scripts.

Thanks!

**Comment by iam-abbas** [comment]
I will look into this!

**Comment by Denbergvanthijs** [comment]
Sorry, my bad. The `limit` argument should be `total` since it is needed to see the estimated ETA. This is due to the fact that `new_bets `is a generator.

This is fixed in this PR: https://github.com/iam-abbas/Reddit-Stock-Trends/pull/4

**Comment by s0meguy1** [comment]
Awesome! I'm out for a few hours, but I'll pull when I get home. Thanks for the quick response!

**Comment by s0meguy1** [comment]
Fix worked, but just an FYI - I had to install python3-lxml via apt. After it started filtering verified ticks, I got a:
```
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/html.py", line 846, in _parser_dispatch
    raise ImportError("lxml not found, please install it")
ImportError: lxml not found, please install it
```

Installing python3-lxml fixed it
