### ISSUE TITLE
Google trends colab:ERROR: Could not find a version that satisfies the requirement numpy==1.20.1

### ISSUE THREAD

**Issue by AngelTiger90** [iam-abbas/Reddit-Stock-Trends#35]
Hi, 
I am trying to use the code in google colab. Some error is displayed.
Any idea why?

!pip install -r requirements.txt

Requirement already satisfied: certifi==2020.12.5 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1)) (2020.12.5)
Collecting chardet==4.0.0
  Downloading https://files.pythonhosted.org/packages/19/c7/fa589626997dd07bd87d9269342ccb74b1720384a4d739a1872bd84fbe68/chardet-4.0.0-py2.py3-none-any.whl (178kB)
     |████████████████████████████████| 184kB 4.9MB/s 
Collecting configparser==5.0.1
  Downloading https://files.pythonhosted.org/packages/08/b2/ef713e0e67f6e7ec7d59aea3ee78d05b39c15930057e724cc6d362a8c3bb/configparser-5.0.1-py3-none-any.whl
Requirement already satisfied: idna==2.10 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 4)) (2.10)
Collecting lxml==4.6.2
  Downloading https://files.pythonhosted.org/packages/bd/78/56a7c88a57d0d14945472535d0df9fb4bbad7d34ede658ec7961635c790e/lxml-4.6.2-cp36-cp36m-manylinux1_x86_64.whl (5.5MB)
     |████████████████████████████████| 5.5MB 7.9MB/s 
Requirement already satisfied: multitasking==0.0.9 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 6)) (0.0.9)
ERROR: Could not find a version that satisfies the requirement numpy==1.20.1 (from -r requirements.txt (line 7)) (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0b3, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.11.1rc1, 1.11.1, 1.11.2rc1, 1.11.2, 1.11.3, 1.12.0b1, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.1rc1, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5)
ERROR: No matching distribution found for numpy==1.20.1 (from -r requirements.txt (line 7))

**Comment by AngelTiger90** [comment]
Sorry if I asked stupid qustion. I am a user only.

**I solved the issue on Google Colab by changing the requirement to:**

certifi==2020.12.5
chardet==3.0.2
configparser==5.0.1
idna==2.10
lxml==4.6.2
multitasking==0.0.9
numpy==1.19.5
pandas==1.1.5
praw==7.0.0
prawcore==1.5.0
python-dateutil==2.8.1
python-dotenv==0.15.0
pytz==2021.1
requests==2.23.0
six==1.15.0
tqdm==4.56.0
update-checker==0.18.0
urllib3==1.24.3
websocket-client==0.57.0
yfinance==0.1.55
flask==1.1.2
flask_cors==3.0.10
folium==0.2.1

!pip install -r requirements.txt
Requirement already satisfied: certifi==2020.12.5 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1)) (2020.12.5)
Requirement already satisfied: chardet==3.0.2 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2)) (3.0.2)
Requirement already satisfied: configparser==5.0.1 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 3)) (5.0.1)
Requirement already satisfied: idna==2.10 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 4)) (2.10)
Requirement already satisfied: lxml==4.6.2 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 5)) (4.6.2)
Requirement already satisfied: multitasking==0.0.9 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 6)) (0.0.9)
Requirement already satisfied: numpy==1.19.5 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 7)) (1.19.5)
Requirement already satisfied: pandas==1.1.5 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 8)) (1.1.5)
Requirement already satisfied: praw==7.0.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 9)) (7.0.0)
Requirement already satisfied: prawcore==1.5.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 10)) (1.5.0)
Requirement already satisfied: python-dateutil==2.8.1 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 11)) (2.8.1)
Requirement already satisfied: python-dotenv==0.15.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 12)) (0.15.0)
Requirement already satisfied: pytz==2021.1 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 13)) (2021.1)
Requirement already satisfied: requests==2.23.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 14)) (2.23.0)
Requirement already satisfied: six==1.15.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 15)) (1.15.0)
Requirement already satisfied: tqdm==4.56.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 16)) (4.56.0)
Requirement already satisfied: update-checker==0.18.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 17)) (0.18.0)
Requirement already satisfied: urllib3==1.24.3 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 18)) (1.24.3)
Requirement already satisfied: websocket-client==0.57.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 19)) (0.57.0)
Requirement already satisfied: yfinance==0.1.55 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 20)) (0.1.55)
Requirement already satisfied: flask==1.1.2 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 21)) (1.1.2)
Requirement already satisfied: flask_cors==3.0.10 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 22)) (3.0.10)
Requirement already satisfied: folium==0.2.1 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 23)) (0.2.1)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.6/dist-packages (from flask==1.1.2->-r requirements.txt (line 21)) (1.0.1)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.6/dist-packages (from flask==1.1.2->-r requirements.txt (line 21)) (1.1.0)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.6/dist-packages (from flask==1.1.2->-r requirements.txt (line 21)) (2.11.3)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python3.6/dist-packages (from flask==1.1.2->-r requirements.txt (line 21)) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/dist-packages (from Jinja2>=2.10.1->flask==1.1.2->-r requirements.txt (line 21)) (1.1.1)


**But,**

**I have the new issue. Any idea how to fix? 

!python ticker_counts.py**



Version 7.0.0 of praw is outdated. Version 7.1.4 was released 2 days ago.
Selecting relevant data from webscraper:   0% 0/2000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "ticker_counts.py", line 45, in <module>
    post.total_awards_received] for post in tqdm(new_bets, desc="Selecting relevant data from webscraper", total=WEBSCRAPER_LIMIT)]
  File "ticker_counts.py", line 40, in <listcomp>
    posts = [[post.id,
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1166, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/praw/models/listing/generator.py", line 61, in __next__
    self._next_batch()
  File "/usr/local/lib/python3.6/dist-packages/praw/models/listing/generator.py", line 71, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/usr/local/lib/python3.6/dist-packages/praw/reddit.py", line 490, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/usr/local/lib/python3.6/dist-packages/praw/reddit.py", line 574, in _objectify_request
    data=data, files=files, method=method, params=params, path=path
  File "/usr/local/lib/python3.6/dist-packages/praw/reddit.py", line 732, in request
    timeout=self.config.timeout,
  File "/usr/local/lib/python3.6/dist-packages/prawcore/sessions.py", line 339, in request
    url=url,
  File "/usr/local/lib/python3.6/dist-packages/prawcore/sessions.py", line 235, in _request_with_retries
    url,
  File "/usr/local/lib/python3.6/dist-packages/prawcore/sessions.py", line 195, in _make_request
    timeout=timeout,
  File "/usr/local/lib/python3.6/dist-packages/prawcore/rate_limit.py", line 35, in call
    kwargs["headers"] = set_header_callback()
  File "/usr/local/lib/python3.6/dist-packages/prawcore/sessions.py", line 282, in _set_header_callback
    self._authorizer.refresh()
  File "/usr/local/lib/python3.6/dist-packages/prawcore/auth.py", line 325, in refresh
    self._request_token(grant_type="client_credentials")
  File "/usr/local/lib/python3.6/dist-packages/prawcore/auth.py", line 153, in _request_token
    response = self._authenticator._post(url, **data)
  File "/usr/local/lib/python3.6/dist-packages/prawcore/auth.py", line 36, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response

**Comment by iam-abbas** [comment]
> prawcore.exceptions.ResponseException: received 401 HTTP response

This basically means your credentials are wrong. Did you create `praw.ini` and add your credentials to it? I am also working on the `requirements.txt` fix, it will be included in the next update

**Comment by iam-abbas** [comment]
@AngelTiger90 you can reopen the issue if it’s still not fixed
