### ISSUE TITLE
Scrape DoughPennyStocks subreddit? 

### ISSUE THREAD

**Issue by m-henderson** [iam-abbas/Reddit-Stock-Trends#42]
could we have the bot scrape the [DoughPennyStocks ](https://www.reddit.com/r/DoughPennyStocks/)subreddit as well?

**Comment by Classic-Paterson** [comment]
You can make this change by modifying the [`config file`](https://github.com/iam-abbas/Reddit-Stock-Trends/blob/main/back/config/config.ini)
