### ISSUE TITLE
PRAW details

### ISSUE THREAD

**Issue by Quinten-gs** [iam-abbas/Reddit-Stock-Trends#5]
A suggestion; Store your details (client-id, client-secret of praw) as variables in a secrets.py file and import the variables from this .py file at the start of your notebook. 

Then in your .gitignore you can add this secrets.py file such that it will not be pushed to github. 

Currently everyone pulling your code is using your account.

**Comment by iam-abbas** [comment]
Yes! I'm going to add the api credentials as env variables. Currently the exposed ones are from a throwaway account that I created just for this.
